class ErrorCode:
    E_MINERU_NOT_FOUND = "E_MINERU_NOT_FOUND"
    E_MINERU_FAILED = "E_MINERU_FAILED"
    E_MINERU_OUTPUT_MISSING = "E_MINERU_OUTPUT_MISSING"
    E_MINERU_TIMEOUT = "E_MINERU_TIMEOUT"
    E_URL_HTML_NOT_SUPPORTED = "E_URL_HTML_NOT_SUPPORTED"
    E_URL_NOT_PDF = "E_URL_NOT_PDF"
    E_UNSUPPORTED_EXT = "E_UNSUPPORTED_EXT"
